In [599]:
import pandas as pd
import numpy as np
from mlxtend.plotting import plot_decision_regions
from sklearn.tree import DecisionTreeClassifier
from mlxtend.plotting import plot_decision_regions

In [600]:
df = pd.DataFrame()
df['X1'] = [1,2,3,4,5,6,6,7,9,9]
df['X2'] = [5,3,6,8,1,9,5,8,9,2]
df['label'] = [1,1,0,1,0,1,0,1,0,0]

In [601]:
def add_weights(df):
    df['weights'] = 1/df.shape[0]

In [602]:
def train_mode(df):
    # features
    X = df.iloc[:,0:2].values
    # label
    y = df.iloc[:,2].values
    # create decesion tree object with max width 1 known as stum
    dt1 = DecisionTreeClassifier(max_depth=1)
    # Step 2 - Train 1st model
    dt1.fit(X,y)
    return dt1;


In [603]:
def append_prediciton(df):
    # append prediction in dataset
    X = df.iloc[:,0:2].values
    df['y_pred'] = dt1.predict(X)

In [604]:
def cal_alpha(df):
    label=df["label"]
    weights=df["weights"]
    
    error=0
    for i in range(len(label)):
        if(label[i]!=y_pred[i]):
            error+=weights[i]

    alpha=0.5*np.log((1-error)/(error))
    return alpha

In [605]:
def update_weights(df):
    #updata weights
    y_pred=df['y_pred']
    label=df["label"]
    weights=df["weights"]
    updated_weights=[0]*10
    for i in range(len(label)):
        if(label[i]!=y_pred[i]):
            updated_weights[i]=weights[i]*np.exp(alpha)
        else:
            updated_weights[i]=weights[i]*np.exp(-alpha) 
    normalize_weights(updated_weights)
    df["updated_weights"]=updated_weights

In [606]:
def normalize_weights(updated_weights):
    #normalize updated weights
    sum=0
    for i in range(len(updated_weights)):
        sum+=updated_weights[i]
    for i in range(len(updated_weights)):
        updated_weights[i]=updated_weights[i]/sum

In [607]:
# create bucket
def create_bucket(df):
    upper_range=[]
    lower_range=[]
    updated_weights=df["updated_weights"]
    for i in range(len(updated_weights)):
        if(i==0):
            upper_range.append(updated_weights[0])
            lower_range.append(0.0)
        else:
            lower_range.append(upper_range[i-1])
            upper_range.append(upper_range[i-1]+updated_weights[i])
    df["lower_range"]=lower_range
    df["upper_range"]=upper_range

In [608]:
def create_new_dataset(df):
    X1=df['X1']
    X2=df['X2']
    label=df['label']
    new_x1=[]
    new_x2=[]
    new_label=[]
    for i in range(len(X)):
        row=random.randint(0,9)
        new_x1.append(X1[row])
        new_x2.append(X2[row])
        new_label.append(label[row])
        
    df1 = pd.DataFrame()
    df1["X1"]=new_x1
    df1["X2"]=new_x2
    df1["label"]=new_label
    return df1

In [609]:
add_weights(df)

In [610]:
dt1=train_mode(df)

In [611]:
append_prediciton(df)

In [612]:
alpha1=cal_alpha(df)
alpha1

0.4236489301936017

In [613]:
update_weights(df)

In [614]:
create_bucket(df)

In [615]:
df1=create_new_dataset(df)

In [616]:
add_weights(df1)

In [617]:
dt2=train_mode(df1)

In [618]:
append_prediciton(df1)

In [619]:
alpha2=cal_alpha(df1)
alpha2

0.2027325540540821

In [620]:
update_weights(df1)

In [621]:
create_bucket(df1)

In [657]:
df2=create_new_dataset(df1)

In [658]:
add_weights(df2)

In [659]:
dt3=train_mode(df2)

In [660]:
append_prediciton(df2)

In [661]:
alpha3=cal_alpha(df2)
alpha3

-0.4236489301936017

In [662]:
update_weights(df2)

In [663]:
create_bucket(df2)

In [728]:
query = np.array([9,2]).reshape(1,2)
dt1.predict(query)

array([0])

In [729]:
dt2.predict(query)

array([0])

In [730]:
dt3.predict(query)

array([0])

In [731]:
alpha1*(-1) + alpha2*(-1) + alpha3*(-1)

-0.20273255405408208

In [733]:
np.sign(-0.20273255405408208)

-1.0

In [734]:
query = np.array([2,3]).reshape(1,2)
dt1.predict(query)

array([1])

In [735]:
dt2.predict(query)

array([0])

In [736]:
dt3.predict(query)

array([0])

In [737]:
alpha1*(1) + alpha2*(1) + alpha3*(-1)

1.0500304144412855

In [738]:
np.sign(0.6445653063331214)

1.0